logPath: ./logs/qt.log
logLevel: debug
baseUrl: "https://api.fcoin.com/v2"
assKey: ""
secretKey: ""
dsn:
symbols:
  -
    balance: "100"
    assetPrecision: "4"
    pricePrecision: "1"
    symbol: "btcusdt"
    minBalance: "10"
    minAsset: "0.001"
    period: "3"
    #1单边交易 2 双边交易
    bySide: "2"
    diffBuyRate: "0.0007"
    diffSellRate: "0.0017"

