logPath: ./logs/qt.log
logLevel: debug
baseUrl: "https://api.fcoin.com/v2"
assKey: ""
secretKey: ""
dsn: ""
symbols:
  -
    balance: "100"
    assetPrecision: "4"
    pricePrecision: "3"
    symbol: "eosusdt"
    minBalance: "10"
    minAsset: "0.01"
    period: "1"
    #1单边交易 2 双边交易
    bySide: "2"
    #1-15 排序挖矿的范围
    buyLowLevel: "3"
    buyLevel: "12"
    buyHighLevel: "16"
    #挂单的范围 1-20
    sellLowLevel: "8"
    sellLevel: "12"
    sellHighLevel: "20"
